module.exports = [
    "stc",
    "stc-eslint",
    "stc-babel",
    "stc-typescript",
    "stc-uglify",
    "stc-dep-parser",
    "stc-plugin",
    "stc-file",
    "stc-cluster",
    "stc-cache",
    "stc-demo",
    "stc-plugin-invoke",
    "stc-helper",
    "stc-replace",
    "stc-log",
    "stc-css-combine",
    "stc-css-compress"
]